### ISSUE TITLE
no longer functions with puppetserver

### ISSUE THREAD

**Issue by mootpt** [rogeduardo/hiera-psql#7]
This backend needs to be updated to use something similar to pg_jruby. I did some testing myself and was unable to get it functioning properly. This update is necessary for the hiera backend to function outside command line calls.

**Comment by lingfish** [comment]
Seems the author has abandoned this repo: https://groups.google.com/d/msg/puppet-users/WVEdyMx1LvM/Fb2_CbuU3V4J

**Comment by dalen** [comment]
Sorry for the late reply. But I'm not using Puppet Server at the moment (running masterless) and I'm also not using this hiera backend at the moment. So if someone else wants to take over maintenance of this hiera backend I'd be happy to move over the ownership.

**Comment by petems** [comment]
@mootpt have you got an example of how you're current setup works?

From my quick tests:

```bash
/opt/puppetlabs/bin/puppetserver gem install pg_jruby
```

seems to work, but it's hard to check if it's properly working from the setup I was using (PE master with the postgres db with a bunch of manual queries to make the right tables)

**Comment by mootpt** [comment]
it's been awhile since I have looked at this. @petems any chance you were able to verify if this is still in issue? or is this good to close?

**Comment by petems** [comment]
I believe there's some performance issues with JRuby Postgres from talking to a user trying to upgrade from Passenger Puppet Master to Puppet Server, but I haven't had a chance to reproduce the issue as it's a fairly complex setup.

**Comment by rogeduardo** [comment]
Dalen, I accept to take maintenance over this project.

**Comment by dalen** [comment]
@rogeduardo Sure, I can transfer ownership to you

**Comment by rogeduardo** [comment]
I have made some improvements for hiera 5. I will consider this issue was closed.
